// AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
// Source: nebula-sdks/openapi/openapi.json

import type { components } from "../types.ts";
import type { NebulaCore, RequestOptions } from "../runtime/client.ts";

export class ClientResource {
  constructor(private readonly core: NebulaCore) {}

  /**
   * Readiness probe
   *
   * Returns 200 only after required bootstrap collections, the database pool, and graph storage are ready to serve requests. Use `/v1/liveness` for a process-only probe.
   * @operationId client.health
   * @endpoint GET /v1/health
   */
  async health(options?: RequestOptions): Promise<components["schemas"]["GenericMessageResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedGenericMessageResponse"]>({
      method: "GET",
      path: "/v1/health",
      pathParams: {},
      query: undefined,
      headers: undefined,
      retryable: true,
      httpSemanticallyIdempotent: true,
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["GenericMessageResponse"] };
    return response.results;
  }

}