// AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
// Source: nebula-sdks/openapi/openapi.json

import type { components } from "../types.ts";
import type { NebulaCore, RequestOptions } from "../runtime/client.ts";

export class ClientResource {
  constructor(private readonly core: NebulaCore) {}

  /**
   * Health probe
   *
   * Lightweight liveness probe. Returns a 200 with a fixed message when the API process is up. Does not verify downstream dependencies (database, storage, workers) — use the internal status endpoints for those.
   * @operationId client.health
   * @endpoint GET /v1/health
   */
  async health(options?: RequestOptions): Promise<components["schemas"]["GenericMessageResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedGenericMessageResponse"]>({
      method: "GET",
      path: "/v1/health",
      pathParams: {},
      query: undefined,
      idempotent: true,
      signal: options?.signal,
    })) as { results: components["schemas"]["GenericMessageResponse"] };
    return response.results;
  }

}