// AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
// Source: nebula-sdks/openapi/openapi.json

import type { components } from "../types.ts";
import { prepareGeneratedBody, type GeneratedBodyInput } from "../runtime/client.ts";
import type { NebulaCore, RequestOptions } from "../runtime/client.ts";

export class CollectionsResource {
  constructor(private readonly core: NebulaCore) {}

  /**
   * Copy collection
   *
   * Copy an existing collection.
   *
   * Starts a durable copy of the collection, including all engrams, chunks,
   * and knowledge graph data (entities, relationships, facts). The response
   * immediately reports whether provisioning is still processing, succeeded,
   * or failed. Retry with the same collection_id to recover the same result.
   *
   * You need at least READ_CONTENT access to the source collection to copy it.
   * For team workspace collections, you must be a workspace owner or admin.
   * @operationId collections.copy
   * @endpoint POST /v1/workspaces/{workspace_id}/collections/{source_collection_id}/copy
   */
  async copy(
    params: {
  /** Workspace that will own the copied collection */
  workspaceId: string;
  /** The unique identifier of the collection to copy */
  sourceCollectionId: string;
  body: GeneratedBodyInput<components["schemas"]["CopyCollectionRequest"], "collection_id">;
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["CollectionMutationResult"]> {
    const response = (await this.core.request<components["schemas"]["WrappedCollectionMutationResult"]>({
      method: "POST",
      path: "/v1/workspaces/{workspace_id}/collections/{source_collection_id}/copy",
      pathParams: { workspace_id: params.workspaceId, source_collection_id: params.sourceCollectionId },
      query: undefined,
      body: prepareGeneratedBody(params.body, [{"path":["collection_id"],"kind":"uuid"}]),
      headers: undefined,
      routing: {
        owner: "workspace",
        pathFields: ["workspace_id","workspaceId"],
      },
      retryable: true,
      httpSemanticallyIdempotent: false,
      mutationReplayIdentity: {"source":"body","name":"collection_id","generated":"uuid"},
      utf8ByteLimits: [{"source":"body","path":["name"],"maximum":256}],
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["CollectionMutationResult"] };
    return response.results;
  }

  /**
   * Create a new collection
   *
   * Create a new collection and automatically add the creating user
   * to it.
   *
   * This endpoint allows authenticated users to create a new collection
   * with a specified name and optional description. The user creating
   * the collection is automatically added as a member.
   * @operationId collections.create
   * @endpoint POST /v1/collections
   */
  async create(
    body: GeneratedBodyInput<components["schemas"]["CreateCollectionRequest"], "collection_id">,
    options?: RequestOptions,
  ): Promise<components["schemas"]["CollectionMutationResult"]> {
    const response = (await this.core.request<components["schemas"]["WrappedCollectionMutationResult"]>({
      method: "POST",
      path: "/v1/collections",
      pathParams: {},
      query: undefined,
      body: prepareGeneratedBody(body, [{"path":["collection_id"],"kind":"uuid"}]),
      headers: undefined,
      routing: {
        owner: "workspace",
        bodyFields: ["workspace_id","workspaceId"],
      },
      retryable: true,
      httpSemanticallyIdempotent: false,
      mutationReplayIdentity: {"source":"body","name":"collection_id","generated":"uuid"},
      utf8ByteLimits: [{"source":"body","path":["name"],"maximum":256}],
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["CollectionMutationResult"] };
    return response.results;
  }

  /**
   * Delete collection
   *
   * Delete an existing collection.
   *
   * This endpoint allows deletion of a collection identified by its
   * UUID. The user must have appropriate permissions to delete the
   * collection. The collection is marked as deleting immediately and
   * data removal continues asynchronously. Memories shared with other
   * collections remain available there; memories exclusive to this
   * collection are removed.
   * @operationId collections.delete
   * @endpoint DELETE /v1/collections/{id}
   */
  async delete(
    id: string,
    options?: RequestOptions,
  ): Promise<components["schemas"]["CollectionMutationResult"]> {
    const response = (await this.core.request<components["schemas"]["WrappedCollectionMutationResult"]>({
      method: "DELETE",
      path: "/v1/collections/{id}",
      pathParams: { id: id },
      query: undefined,
      headers: undefined,
      retryable: true,
      httpSemanticallyIdempotent: true,
      mutationReplayIdentity: {"source":"intrinsic","name":"resource_path"},
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["CollectionMutationResult"] };
    return response.results;
  }

  /**
   * List collections
   *
   * Returns a cursor-paginated list of collections the authenticated
   * user has access to.
   *
   * Results can be filtered by providing specific collection IDs.
   * Regular users will only see collections they own or have access to.
   * Superusers can see all collections.
   *
   * The collections are returned in order of last modification, with
   * most recent first.
   * @operationId collections.list
   * @endpoint GET /v1/collections
   */
  async list(
    params: {
  /** A list of collection IDs to retrieve. If not provided, all collections will be returned. */
  ids?: Array<string>;
  /** Filter collections by name (case-insensitive exact match). */
  name?: string | null;
  /** Opaque pagination cursor. Pass the ``next_cursor`` from a previous response to fetch the next page. */
  cursor?: string | null;
  /** Specifies a limit on the number of objects to return, ranging between 1 and 1000. Defaults to 100. */
  limit?: number;
  /** If true, only returns collections owned by the user, not all accessible collections. */
  ownerOnly?: boolean;
  /** Filter by workspace ID. Pass a UUID to scope to a workspace, or omit for all. */
  workspaceId?: string | null;
} = {},
    options?: RequestOptions,
  ): Promise<components["schemas"]["PaginatedCollectionResponse"]> {
    return this.core.request<components["schemas"]["PaginatedCollectionResponse"]>({
      method: "GET",
      path: "/v1/collections",
      pathParams: {},
      query: { ids: params.ids, name: params.name, cursor: params.cursor, limit: params.limit, owner_only: params.ownerOnly, workspace_id: params.workspaceId },
      headers: undefined,
      retryable: true,
      httpSemanticallyIdempotent: true,
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    });
  }

  /**
   * Get collection details
   *
   * Get details of a specific collection.
   *
   * This endpoint retrieves detailed information about a single
   * collection identified by its UUID. The user must have access to the
   * collection to view its details.
   * @operationId collections.retrieve
   * @endpoint GET /v1/collections/{id}
   */
  async retrieve(
    id: string,
    options?: RequestOptions,
  ): Promise<components["schemas"]["CollectionResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedCollectionResponse"]>({
      method: "GET",
      path: "/v1/collections/{id}",
      pathParams: { id: id },
      query: undefined,
      headers: undefined,
      retryable: true,
      httpSemanticallyIdempotent: true,
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["CollectionResponse"] };
    return response.results;
  }

  /**
   * Get a collection by name
   *
   * Retrieve a collection by its (owner_id, name) combination.
   *
   * The authenticated user can only fetch collections they own, or, if
   * superuser, from anyone.
   * @operationId collections.retrieveByName
   * @endpoint GET /v1/collections/name/{collection_name}
   */
  async retrieveByName(
    params: {
  /** The name of the collection */
  collectionName: string;
  /** (Superuser only) Specify the owner_id to retrieve a collection by name */
  ownerId?: string | null;
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["CollectionResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedCollectionResponse"]>({
      method: "GET",
      path: "/v1/collections/name/{collection_name}",
      pathParams: { collection_name: params.collectionName },
      query: { owner_id: params.ownerId },
      headers: undefined,
      retryable: true,
      httpSemanticallyIdempotent: true,
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["CollectionResponse"] };
    return response.results;
  }

  /**
   * Update collection
   *
   * Update an existing collection's configuration.
   *
   * This endpoint allows updating the name, description, and access settings of an
   * existing collection. The user must have appropriate permissions to
   * modify the collection.
   * @operationId collections.update
   * @endpoint POST /v1/collections/{id}
   */
  async update(
    params: {
  /** The unique identifier of the collection to update */
  id: string;
  body: components["schemas"]["UpdateCollectionRequest"];
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["CollectionResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedCollectionResponse"]>({
      method: "POST",
      path: "/v1/collections/{id}",
      pathParams: { id: params.id },
      query: undefined,
      body: params.body,
      headers: undefined,
      retryable: false,
      httpSemanticallyIdempotent: false,
      utf8ByteLimits: [{"source":"body","path":["name"],"maximum":256}],
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["CollectionResponse"] };
    return response.results;
  }

}