// AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
// Source: nebula-sdks/openapi/openapi.json

import type { components } from "../types.ts";
import type { NebulaCore } from "../runtime/client.ts";

export interface RequestOptions {
  signal?: AbortSignal;
}

export class CollectionsResource {
  constructor(private readonly core: NebulaCore) {}

  /**
   *
   * Create a new collection
   * 
   * Create a new collection and automatically add the creating user
   * to it.
   * 
   * This endpoint allows authenticated users to create a new collection
   * with a specified name and optional description. The user creating
   * the collection is automatically added as a member.
   * @operationId collections.create
   * @endpoint POST /v1/collections
   */
  async create(
    params: {
  body: components["schemas"]["CreateCollectionRequest"];
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["WrappedCollectionResponse"]> {
    return this.core.request<components["schemas"]["WrappedCollectionResponse"]>({
      method: "POST",
      path: "/v1/collections",
      pathParams: {},
      query: undefined,
      body: params.body,
      idempotent: false,
      signal: options?.signal,
    });
  }

  /**
   *
   * Delete collection
   * 
   * Delete an existing collection.
   * 
   * This endpoint allows deletion of a collection identified by its
   * UUID. The user must have appropriate permissions to delete the
   * collection. Deleting a collection removes all associations but does
   * not delete the engrams within it.
   * @operationId collections.delete
   * @endpoint DELETE /v1/collections/{id}
   */
  async delete(
    id: string,
    options?: RequestOptions,
  ): Promise<components["schemas"]["WrappedGenericBooleanResponse"]> {
    return this.core.request<components["schemas"]["WrappedGenericBooleanResponse"]>({
      method: "DELETE",
      path: "/v1/collections/{id}",
      pathParams: { id: id },
      query: undefined,
      idempotent: true,
      signal: options?.signal,
    });
  }

  /**
   *
   * List collections
   * 
   * Returns a cursor-paginated list of collections the authenticated
   * user has access to.
   * 
   * Results can be filtered by providing specific collection IDs.
   * Regular users will only see collections they own or have access to.
   * Superusers can see all collections.
   * 
   * The collections are returned in order of last modification, with
   * most recent first.
   * @operationId collections.list
   * @endpoint GET /v1/collections
   */
  async list(
    params: {
  /** A list of collection IDs to retrieve. If not provided, all collections will be returned. */
  ids?: Array<string>;
  /** Filter collections by name (case-insensitive exact match). */
  name?: string | null;
  /** Opaque pagination cursor. Pass the ``next_cursor`` from a previous response to fetch the next page. */
  cursor?: string | null;
  /** Specifies a limit on the number of objects to return, ranging between 1 and 1000. Defaults to 100. */
  limit?: number;
  /** If true, only returns collections owned by the user, not all accessible collections. */
  ownerOnly?: boolean;
  /** Filter by workspace ID. Pass a UUID to scope to a workspace, or omit for all. */
  workspaceId?: string | null;
} = {},
    options?: RequestOptions,
  ): Promise<components["schemas"]["PaginatedCollectionResponse"]> {
    return this.core.request<components["schemas"]["PaginatedCollectionResponse"]>({
      method: "GET",
      path: "/v1/collections",
      pathParams: {},
      query: { ids: params.ids, name: params.name, cursor: params.cursor, limit: params.limit, owner_only: params.ownerOnly, workspace_id: params.workspaceId },
      idempotent: true,
      signal: options?.signal,
    });
  }

  /**
   *
   * Get collection details
   * 
   * Get details of a specific collection.
   * 
   * This endpoint retrieves detailed information about a single
   * collection identified by its UUID. The user must have access to the
   * collection to view its details.
   * @operationId collections.retrieve
   * @endpoint GET /v1/collections/{id}
   */
  async retrieve(
    id: string,
    options?: RequestOptions,
  ): Promise<components["schemas"]["WrappedCollectionResponse"]> {
    return this.core.request<components["schemas"]["WrappedCollectionResponse"]>({
      method: "GET",
      path: "/v1/collections/{id}",
      pathParams: { id: id },
      query: undefined,
      idempotent: true,
      signal: options?.signal,
    });
  }

  /**
   *
   * Get a collection by name
   * 
   * Retrieve a collection by its (owner_id, name) combination.
   * 
   * The authenticated user can only fetch collections they own, or, if
   * superuser, from anyone.
   * @operationId collections.retrieveByName
   * @endpoint GET /v1/collections/name/{collection_name}
   */
  async retrieveByName(
    params: {
  /** The name of the collection */
  collectionName: string;
  /** (Superuser only) Specify the owner_id to retrieve a collection by name */
  ownerId?: string | null;
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["WrappedCollectionResponse"]> {
    return this.core.request<components["schemas"]["WrappedCollectionResponse"]>({
      method: "GET",
      path: "/v1/collections/name/{collection_name}",
      pathParams: { collection_name: params.collectionName },
      query: { owner_id: params.ownerId },
      idempotent: true,
      signal: options?.signal,
    });
  }

  /**
   *
   * Update collection
   * 
   * Update an existing collection's configuration.
   * 
   * This endpoint allows updating the name, description, and access settings of an
   * existing collection. The user must have appropriate permissions to
   * modify the collection.
   * @operationId collections.update
   * @endpoint POST /v1/collections/{id}
   */
  async update(
    params: {
  /** The unique identifier of the collection to update */
  id: string;
  body: components["schemas"]["UpdateCollectionRequest"];
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["WrappedCollectionResponse"]> {
    return this.core.request<components["schemas"]["WrappedCollectionResponse"]>({
      method: "POST",
      path: "/v1/collections/{id}",
      pathParams: { id: params.id },
      query: undefined,
      body: params.body,
      idempotent: false,
      signal: options?.signal,
    });
  }

}