// AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
// Source: nebula-sdks/openapi/openapi.json + nebula-sdks/config/sdk-resource-map.yaml

import type { components } from "../types.ts";
import type { NebulaCore } from "../runtime/client.ts";

export interface RequestOptions {
  signal?: AbortSignal;
}

export class ConnectorsResource {
  constructor(private readonly core: NebulaCore) {}

  /**
   *
   * Start OAuth connection flow
   * 
   * Start the OAuth connection flow for the given external provider. Returns the authorization URL the user should visit to grant Nebula access. After consent the provider redirects back to Nebula and the connection becomes active.
   * @operationId connectors.connect
   * @endpoint POST /v1/connectors/{provider}/connect
   */
  async connect(
    params: {
  provider: string;
  body: components["schemas"]["ConnectRequest"];
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["NebulaResults_ConnectorConnectResponse_"]> {
    return this.core.request<components["schemas"]["NebulaResults_ConnectorConnectResponse_"]>({
      method: "POST",
      path: "/v1/connectors/{provider}/connect",
      pathParams: { provider: params.provider },
      query: undefined,
      body: params.body,
      idempotent: false,
      signal: options?.signal,
    });
  }

  /**
   *
   * Disconnect an external data source
   * 
   * Disconnect the named connection, revoking the stored OAuth credentials and stopping future syncs. Optionally pass `delete_memories=true` to also remove every memory this connection had ingested.
   * @operationId connectors.disconnect
   * @endpoint DELETE /v1/connectors/{connection_id}
   */
  async disconnect(
    params: {
  connectionId: string;
  deleteMemories?: boolean;
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["NebulaResults_ConnectorDisconnectResponse_"]> {
    return this.core.request<components["schemas"]["NebulaResults_ConnectorDisconnectResponse_"]>({
      method: "DELETE",
      path: "/v1/connectors/{connection_id}",
      pathParams: { connection_id: params.connectionId },
      query: { delete_memories: params.deleteMemories },
      idempotent: false,
      signal: options?.signal,
    });
  }

  /**
   *
   * List active connections for a collection
   * 
   * Return every connector connection associated with the given collection, with encrypted credentials redacted. Useful for showing the user which third-party data sources are wired up to a collection.
   * @operationId connectors.list
   * @endpoint GET /v1/connectors
   */
  async list(
    params: {
  collectionId: string;
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["NebulaResults_list_ConnectorConnectionResponse__"]> {
    return this.core.request<components["schemas"]["NebulaResults_list_ConnectorConnectionResponse__"]>({
      method: "GET",
      path: "/v1/connectors",
      pathParams: {},
      query: { collection_id: params.collectionId },
      idempotent: true,
      signal: options?.signal,
    });
  }

  /**
   *
   * List available connector providers
   * 
   * Return the set of connector provider identifiers (e.g. `google_drive`, `slack`) that this Nebula instance is configured to expose. Pass one of these to `POST /connectors/{provider}/connect` to start an OAuth flow.
   * @operationId connectors.listProviders
   * @endpoint GET /v1/connectors/providers
   */
  async listProviders(options?: RequestOptions): Promise<components["schemas"]["NebulaResults_list_str__"]> {
    return this.core.request<components["schemas"]["NebulaResults_list_str__"]>({
      method: "GET",
      path: "/v1/connectors/providers",
      pathParams: {},
      query: undefined,
      idempotent: true,
      signal: options?.signal,
    });
  }

  /**
   *
   * Get a single connection by ID
   * 
   * Fetch a single connector connection by its UUID. Returns the connection metadata plus whether the underlying subscription is active. Encrypted credentials are never returned to clients.
   * @operationId connectors.retrieve
   * @endpoint GET /v1/connectors/{connection_id}
   */
  async retrieve(
    connectionId: string,
    options?: RequestOptions,
  ): Promise<components["schemas"]["NebulaResults_ConnectorConnectionResponse_"]> {
    return this.core.request<components["schemas"]["NebulaResults_ConnectorConnectionResponse_"]>({
      method: "GET",
      path: "/v1/connectors/{connection_id}",
      pathParams: { connection_id: connectionId },
      query: undefined,
      idempotent: true,
      signal: options?.signal,
    });
  }

  /**
   *
   * Manually trigger a sync
   * 
   * Schedule an immediate sync for an active connection, bypassing the normal cadence. Returns 409 if a sync is already in progress and 400 if the connection isn't in the `active` state.
   * @operationId connectors.sync
   * @endpoint POST /v1/connectors/{connection_id}/sync
   */
  async sync(
    connectionId: string,
    options?: RequestOptions,
  ): Promise<components["schemas"]["NebulaResults_ConnectorSyncResponse_"]> {
    return this.core.request<components["schemas"]["NebulaResults_ConnectorSyncResponse_"]>({
      method: "POST",
      path: "/v1/connectors/{connection_id}/sync",
      pathParams: { connection_id: connectionId },
      query: undefined,
      idempotent: false,
      signal: options?.signal,
    });
  }

}