// AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
// Source: nebula-sdks/openapi/openapi.json

import type { components } from "../types.ts";
import type { NebulaCore, RequestOptions } from "../runtime/client.ts";

export class ConnectorsResource {
  constructor(private readonly core: NebulaCore) {}

  /**
   * Approve a mass-withdrawal plan
   *
   * Approve exactly the reviewed candidate set and schedule a new sync. Any change to that set requires a new approval.
   * @operationId connectors.approveWithdrawalPlan
   * @endpoint POST /v1/connectors/{connection_id}/withdrawal-plan/{candidate_digest}/approve
   */
  async approveWithdrawalPlan(
    params: {
  connectionId: string;
  candidateDigest: string;
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["ConnectorSyncResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedConnectorSyncResponse"]>({
      method: "POST",
      path: "/v1/connectors/{connection_id}/withdrawal-plan/{candidate_digest}/approve",
      pathParams: { connection_id: params.connectionId, candidate_digest: params.candidateDigest },
      query: undefined,
      headers: undefined,
      retryable: false,
      httpSemanticallyIdempotent: false,
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["ConnectorSyncResponse"] };
    return response.results;
  }

  /**
   * Start OAuth connection flow
   *
   * Start the OAuth connection flow for the given external provider. Returns the authorization URL the user should visit to grant Nebula access. After consent the provider redirects back to Nebula and the connection becomes active.
   * @operationId connectors.connect
   * @endpoint POST /v1/connectors/{provider}/connect
   */
  async connect(
    params: {
  provider: string;
  body: components["schemas"]["ConnectRequest"];
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["ConnectorConnectResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedConnectorConnectResponse"]>({
      method: "POST",
      path: "/v1/connectors/{provider}/connect",
      pathParams: { provider: params.provider },
      query: undefined,
      body: params.body,
      headers: undefined,
      retryable: false,
      httpSemanticallyIdempotent: false,
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["ConnectorConnectResponse"] };
    return response.results;
  }

  /**
   * Disconnect an external data source
   *
   * Disconnect the named connection, revoking the stored OAuth credentials and stopping future syncs. Optionally pass `delete_memories=true` to also remove every memory this connection had ingested.
   * @operationId connectors.disconnect
   * @endpoint DELETE /v1/connectors/{connection_id}
   */
  async disconnect(
    params: {
  connectionId: string;
  deleteMemories?: boolean;
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["ConnectorDisconnectResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedConnectorDisconnectResponse"]>({
      method: "DELETE",
      path: "/v1/connectors/{connection_id}",
      pathParams: { connection_id: params.connectionId },
      query: { delete_memories: params.deleteMemories },
      headers: undefined,
      retryable: false,
      httpSemanticallyIdempotent: true,
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["ConnectorDisconnectResponse"] };
    return response.results;
  }

  /**
   * List active connections for a collection
   *
   * Return every connector connection associated with the given collection, with encrypted credentials redacted. Useful for showing the user which third-party data sources are wired up to a collection.
   * @operationId connectors.list
   * @endpoint GET /v1/connectors
   */
  async list(
    params: {
  collectionId: string;
},
    options?: RequestOptions,
  ): Promise<Array<components["schemas"]["ConnectorConnectionResponse"]>> {
    const response = (await this.core.request<components["schemas"]["WrappedListOfConnectorConnectionResponse"]>({
      method: "GET",
      path: "/v1/connectors",
      pathParams: {},
      query: { collection_id: params.collectionId },
      headers: undefined,
      retryable: true,
      httpSemanticallyIdempotent: true,
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: Array<components["schemas"]["ConnectorConnectionResponse"]> };
    return response.results;
  }

  /**
   * List workspace connector OAuth app registrations
   *
   * Return the workspace-level OAuth app registrations used by Google and Microsoft 365 connectors for the requested collection's workspace. Client secrets are never returned.
   * @operationId connectors.listOAuthApps
   * @endpoint GET /v1/connectors/oauth-apps
   */
  async listOAuthApps(
    params: {
  collectionId: string;
},
    options?: RequestOptions,
  ): Promise<Array<components["schemas"]["ConnectorOAuthAppResponse"]>> {
    const response = (await this.core.request<components["schemas"]["WrappedListOfConnectorOAuthAppResponse"]>({
      method: "GET",
      path: "/v1/connectors/oauth-apps",
      pathParams: {},
      query: { collection_id: params.collectionId },
      headers: undefined,
      retryable: true,
      httpSemanticallyIdempotent: true,
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: Array<components["schemas"]["ConnectorOAuthAppResponse"]> };
    return response.results;
  }

  /**
   * List available connector providers
   *
   * Return the set of connector provider identifiers (e.g. `google_drive`, `slack`) that this Nebula instance is configured to expose. Pass one of these to `POST /connectors/{provider}/connect` to start an OAuth flow.
   * @operationId connectors.listProviders
   * @endpoint GET /v1/connectors/providers
   */
  async listProviders(options?: RequestOptions): Promise<Array<string>> {
    const response = (await this.core.request<components["schemas"]["WrappedListOfStr"]>({
      method: "GET",
      path: "/v1/connectors/providers",
      pathParams: {},
      query: undefined,
      headers: undefined,
      retryable: true,
      httpSemanticallyIdempotent: true,
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: Array<string> };
    return response.results;
  }

  /**
   * Retry a failed source withdrawal
   *
   * Reset a terminally failed deletion handoff and schedule a new bounded deletion attempt.
   * @operationId connectors.requeueWithdrawal
   * @endpoint POST /v1/connectors/{connection_id}/withdrawals/{engram_id}/requeue
   */
  async requeueWithdrawal(
    params: {
  connectionId: string;
  engramId: string;
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["ConnectorSyncResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedConnectorSyncResponse"]>({
      method: "POST",
      path: "/v1/connectors/{connection_id}/withdrawals/{engram_id}/requeue",
      pathParams: { connection_id: params.connectionId, engram_id: params.engramId },
      query: undefined,
      headers: undefined,
      retryable: false,
      httpSemanticallyIdempotent: false,
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["ConnectorSyncResponse"] };
    return response.results;
  }

  /**
   * Get a single connection by ID
   *
   * Fetch a single connector connection by its UUID. Returns the connection metadata plus whether the underlying subscription is active. Encrypted credentials are never returned to clients.
   * @operationId connectors.retrieve
   * @endpoint GET /v1/connectors/{connection_id}
   */
  async retrieve(
    connectionId: string,
    options?: RequestOptions,
  ): Promise<components["schemas"]["ConnectorConnectionResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedConnectorConnectionResponse"]>({
      method: "GET",
      path: "/v1/connectors/{connection_id}",
      pathParams: { connection_id: connectionId },
      query: undefined,
      headers: undefined,
      retryable: true,
      httpSemanticallyIdempotent: true,
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["ConnectorConnectionResponse"] };
    return response.results;
  }

  /**
   * Get a pending mass-withdrawal plan
   *
   * Return the operator-review plan created when a sync would remove more source items than the connection's automatic safety allowance.
   * @operationId connectors.retrieveWithdrawalPlan
   * @endpoint GET /v1/connectors/{connection_id}/withdrawal-plan
   */
  async retrieveWithdrawalPlan(
    connectionId: string,
    options?: RequestOptions,
  ): Promise<components["schemas"]["ConnectorWithdrawalPlanResponse"] | null> {
    const response = (await this.core.request<components["schemas"]["WrappedConnectorWithdrawalPlanResponseOrNoneType"]>({
      method: "GET",
      path: "/v1/connectors/{connection_id}/withdrawal-plan",
      pathParams: { connection_id: connectionId },
      query: undefined,
      headers: undefined,
      retryable: true,
      httpSemanticallyIdempotent: true,
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["ConnectorWithdrawalPlanResponse"] | null };
    return response.results;
  }

  /**
   * Manually trigger a sync
   *
   * Schedule an immediate sync for an active connection, bypassing the normal cadence. Returns 409 if a sync is already in progress and 400 if the connection isn't in the `active` state.
   * @operationId connectors.sync
   * @endpoint POST /v1/connectors/{connection_id}/sync
   */
  async sync(
    connectionId: string,
    options?: RequestOptions,
  ): Promise<components["schemas"]["ConnectorSyncResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedConnectorSyncResponse"]>({
      method: "POST",
      path: "/v1/connectors/{connection_id}/sync",
      pathParams: { connection_id: connectionId },
      query: undefined,
      headers: undefined,
      retryable: false,
      httpSemanticallyIdempotent: false,
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["ConnectorSyncResponse"] };
    return response.results;
  }

  /**
   * Update a workspace connector OAuth app
   *
   * Update non-secret workspace OAuth app settings for a collection's workspace. Google apps can provide Pub/Sub settings to enable Gmail real-time sync. Client secrets are never returned.
   * @operationId connectors.updateOAuthApp
   * @endpoint PATCH /v1/connectors/oauth-apps/{provider_family}
   */
  async updateOAuthApp(
    params: {
  providerFamily: string;
  body: components["schemas"]["ConnectorOAuthAppUpdateRequest"];
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["ConnectorOAuthAppResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedConnectorOAuthAppResponse"]>({
      method: "PATCH",
      path: "/v1/connectors/oauth-apps/{provider_family}",
      pathParams: { provider_family: params.providerFamily },
      query: undefined,
      body: params.body,
      headers: undefined,
      retryable: false,
      httpSemanticallyIdempotent: false,
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["ConnectorOAuthAppResponse"] };
    return response.results;
  }

}