// AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
// Source: nebula-sdks/openapi/openapi.json

import type { components } from "../types.ts";
import { prepareGeneratedBody, type GeneratedBodyInput } from "../runtime/client.ts";
import type { NebulaCore, RequestOptions } from "../runtime/client.ts";

export class EnterpriseResource {
  constructor(private readonly core: NebulaCore) {}

  /**
   * Provision an enterprise account
   *
   * Create a user, named collection, and API key as one operation.
   * @operationId enterprise.provisionAccount
   * @endpoint POST /v1/admin/enterprise-provisioning
   */
  async provisionAccount(
    body: GeneratedBodyInput<components["schemas"]["EnterpriseProvisioningRequest"], "request_id">,
    options?: RequestOptions,
  ): Promise<components["schemas"]["EnterpriseProvisioningResult"]> {
    const response = (await this.core.request<components["schemas"]["WrappedEnterpriseProvisioningResult"]>({
      method: "POST",
      path: "/v1/admin/enterprise-provisioning",
      pathParams: {},
      query: undefined,
      body: prepareGeneratedBody(body, [{"path":["request_id"],"kind":"uuid"}]),
      headers: undefined,
      retryable: true,
      httpSemanticallyIdempotent: false,
      mutationReplayIdentity: {"source":"body","name":"request_id","generated":"uuid"},
      utf8ByteLimits: [{"source":"body","path":["collection_name"],"maximum":256}],
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["EnterpriseProvisioningResult"] };
    return response.results;
  }

}