// AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
// Source: nebula-sdks/openapi/openapi.json

import type { components } from "../types.ts";
import { prepareGeneratedBody, type GeneratedBodyInput } from "../runtime/client.ts";
import type { NebulaCore, RequestOptions } from "../runtime/client.ts";

export class IngestionOperationResource {
  constructor(private readonly core: NebulaCore) {}

  /**
   * Cancel an ingestion operation
   *
   * Cancel unfinished items and fence their active generations.
   * @operationId ingestionOperation.cancel
   * @endpoint POST /v1/ingestion-operations/{operation_id}/cancel
   */
  async cancel(
    operationId: string,
    options?: RequestOptions,
  ): Promise<components["schemas"]["IngestionOperationStatus"]> {
    const response = (await this.core.request<components["schemas"]["WrappedIngestionOperationStatus"]>({
      method: "POST",
      path: "/v1/ingestion-operations/{operation_id}/cancel",
      pathParams: { operation_id: operationId },
      query: undefined,
      headers: undefined,
      retryable: true,
      httpSemanticallyIdempotent: false,
      mutationReplayIdentity: {"source":"intrinsic","name":"operation_id"},
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["IngestionOperationStatus"] };
    return response.results;
  }

  /**
   * Create an ingestion operation
   *
   * Create an open ingestion operation for one collection.
   * @operationId ingestionOperation.create
   * @endpoint POST /v1/ingestion-operations
   */
  async create(
    body: GeneratedBodyInput<components["schemas"]["CreateIngestionOperationRequest"], "operation_id">,
    options?: RequestOptions,
  ): Promise<components["schemas"]["IngestionOperationStatus"]> {
    const response = (await this.core.request<components["schemas"]["WrappedIngestionOperationStatus"]>({
      method: "POST",
      path: "/v1/ingestion-operations",
      pathParams: {},
      query: undefined,
      body: prepareGeneratedBody(body, [{"path":["operation_id"],"kind":"uuid"}]),
      headers: undefined,
      routing: {
        owner: "collection",
        bodyFields: ["collection_id","collectionId"],
      },
      retryable: true,
      httpSemanticallyIdempotent: false,
      mutationReplayIdentity: {"source":"body","name":"operation_id","generated":"uuid"},
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["IngestionOperationStatus"] };
    return response.results;
  }

  /**
   * Get an ingestion operation
   *
   * Get per-item ingestion, search, and processing readiness.
   * @operationId ingestionOperation.get
   * @endpoint GET /v1/ingestion-operations/{operation_id}
   */
  async get(
    operationId: string,
    options?: RequestOptions,
  ): Promise<components["schemas"]["IngestionOperationStatus"]> {
    const response = (await this.core.request<components["schemas"]["WrappedIngestionOperationStatus"]>({
      method: "GET",
      path: "/v1/ingestion-operations/{operation_id}",
      pathParams: { operation_id: operationId },
      query: undefined,
      headers: undefined,
      retryable: true,
      httpSemanticallyIdempotent: true,
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["IngestionOperationStatus"] };
    return response.results;
  }

  /**
   * Get batched ingestion operation status
   *
   * Get ordered status views for multiple ingestion operations.
   * @operationId ingestionOperation.getMany
   * @endpoint POST /v1/ingestion-operations/status
   */
  async getMany(
    body: components["schemas"]["BatchedOperationStatusRequest"],
    options?: RequestOptions,
  ): Promise<components["schemas"]["BatchedOperationStatusResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedBatchedOperationStatusResponse"]>({
      method: "POST",
      path: "/v1/ingestion-operations/status",
      pathParams: {},
      query: undefined,
      body: body,
      headers: undefined,
      retryable: true,
      httpSemanticallyIdempotent: false,
      mutationReplayIdentity: {"source":"intrinsic","name":"resource_set"},
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["BatchedOperationStatusResponse"] };
    return response.results;
  }

  /**
   * Add or replay an ingestion operation item
   *
   * Add or replay one memory under a stable client item key.
   * @operationId ingestionOperation.putItem
   * @endpoint PUT /v1/ingestion-operations/{operation_id}/items
   */
  async putItem(
    params: {
  operationId: string;
  body: GeneratedBodyInput<components["schemas"]["IngestionOperationItemInput"], "memory_id">;
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["IngestionOperationStatus"]> {
    const response = (await this.core.request<components["schemas"]["WrappedIngestionOperationStatus"]>({
      method: "PUT",
      path: "/v1/ingestion-operations/{operation_id}/items",
      pathParams: { operation_id: params.operationId },
      query: undefined,
      body: prepareGeneratedBody(params.body, [{"path":["memory","memory_id"],"kind":"uuid"}]),
      headers: undefined,
      retryable: true,
      httpSemanticallyIdempotent: true,
      mutationReplayIdentity: {"source":"body","name":"item_key"},
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["IngestionOperationStatus"] };
    return response.results;
  }

  /**
   * Seal an ingestion operation
   *
   * Seal an operation so its item set cannot change.
   * @operationId ingestionOperation.seal
   * @endpoint POST /v1/ingestion-operations/{operation_id}/seal
   */
  async seal(
    operationId: string,
    options?: RequestOptions,
  ): Promise<components["schemas"]["IngestionOperationStatus"]> {
    const response = (await this.core.request<components["schemas"]["WrappedIngestionOperationStatus"]>({
      method: "POST",
      path: "/v1/ingestion-operations/{operation_id}/seal",
      pathParams: { operation_id: operationId },
      query: undefined,
      headers: undefined,
      retryable: true,
      httpSemanticallyIdempotent: false,
      mutationReplayIdentity: {"source":"intrinsic","name":"operation_id"},
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["IngestionOperationStatus"] };
    return response.results;
  }

  /**
   * Wait for ingestion operation search visibility
   *
   * Wait until successful items are visible to memory search.
   * @operationId ingestionOperation.searchBarrier
   * @endpoint POST /v1/ingestion-operations/search-barrier
   */
  async searchBarrier(
    body: components["schemas"]["SearchBarrierRequest"],
    options?: RequestOptions,
  ): Promise<components["schemas"]["SearchBarrierResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedSearchBarrierResponse"]>({
      method: "POST",
      path: "/v1/ingestion-operations/search-barrier",
      pathParams: {},
      query: undefined,
      body: body,
      headers: undefined,
      retryable: true,
      httpSemanticallyIdempotent: false,
      mutationReplayIdentity: {"source":"intrinsic","name":"resource_set"},
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["SearchBarrierResponse"] };
    return response.results;
  }

}