// AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
// Source: nebula-sdks/openapi/openapi.json

import type { components } from "../types.ts";
import { prepareGeneratedBody, type GeneratedBodyInput } from "../runtime/client.ts";
import type { NebulaCore, RequestOptions } from "../runtime/client.ts";

export class MarketplaceResource {
  constructor(private readonly core: NebulaCore) {}

  /**
   * Fork a public collection into a workspace
   *
   * Fork a public collection into a workspace.
   *
   * The response reports whether the durable copy is still processing,
   * succeeded, or failed. Retry with the same collection_id to recover
   * the same result.
   *
   * Authentication is required. The forked collection counts toward your plan limits.
   * @operationId marketplace.fork
   * @endpoint POST /v1/workspaces/{workspace_id}/marketplace/collections/{source_collection_id}/fork
   */
  async fork(
    params: {
  /** Workspace that will own the fork */
  workspaceId: string;
  /** The ID of the collection to fork */
  sourceCollectionId: string;
  body: GeneratedBodyInput<components["schemas"]["ForkMarketplaceCollectionRequest"], "collection_id">;
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["CollectionMutationResult"]> {
    const response = (await this.core.request<components["schemas"]["WrappedCollectionMutationResult"]>({
      method: "POST",
      path: "/v1/workspaces/{workspace_id}/marketplace/collections/{source_collection_id}/fork",
      pathParams: { workspace_id: params.workspaceId, source_collection_id: params.sourceCollectionId },
      query: undefined,
      body: prepareGeneratedBody(params.body, [{"path":["collection_id"],"kind":"uuid"}]),
      headers: undefined,
      routing: {
        owner: "workspace",
        pathFields: ["workspace_id","workspaceId"],
      },
      retryable: true,
      httpSemanticallyIdempotent: false,
      mutationReplayIdentity: {"source":"body","name":"collection_id","generated":"uuid"},
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["CollectionMutationResult"] };
    return response.results;
  }

  /**
   * Get details of a public collection
   *
   * Get details of a public collection from the marketplace.
   * Returns collection metadata including pricing, preview limits, etc.
   * @operationId marketplace.getCollection
   * @endpoint GET /v1/marketplace/collections/{collection_id}
   */
  async getCollection(
    collectionId: string,
    options?: RequestOptions,
  ): Promise<components["schemas"]["CollectionResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedCollectionResponse"]>({
      method: "GET",
      path: "/v1/marketplace/collections/{collection_id}",
      pathParams: { collection_id: collectionId },
      query: undefined,
      headers: undefined,
      retryable: true,
      httpSemanticallyIdempotent: true,
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["CollectionResponse"] };
    return response.results;
  }

  /**
   * Browse public marketplace collections
   *
   * Browse publicly available collections in the marketplace.
   * These collections have 'public_preview' or 'marketplace' access tier.
   *
   * No authentication required, but authenticated users may see more details.
   * @operationId marketplace.listCollections
   * @endpoint GET /v1/marketplace/collections
   */
  async listCollections(
    params: {
  /** Opaque pagination cursor. Pass the ``next_cursor`` from a previous response to fetch the next page. */
  cursor?: string | null;
  /** The maximum number of collections to return */
  limit?: number;
  /** Search query to filter collections by name or description */
  search?: string | null;
} = {},
    options?: RequestOptions,
  ): Promise<components["schemas"]["PaginatedCollectionResponse"]> {
    return this.core.request<components["schemas"]["PaginatedCollectionResponse"]>({
      method: "GET",
      path: "/v1/marketplace/collections",
      pathParams: {},
      query: { cursor: params.cursor, limit: params.limit, search: params.search },
      headers: undefined,
      retryable: true,
      httpSemanticallyIdempotent: true,
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    });
  }

}