// AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
// Source: nebula-sdks/openapi/openapi.json

import type { components } from "../types.ts";
import type { NebulaCore, RequestOptions } from "../runtime/client.ts";

export class MarketplaceResource {
  constructor(private readonly core: NebulaCore) {}

  /**
   * Get details of a public collection
   *
   * Get details of a public collection from the marketplace.
   * Returns collection metadata including pricing, preview limits, etc.
   * @operationId marketplace.getCollection
   * @endpoint GET /v1/marketplace/collections/{collection_id}
   */
  async getCollection(
    collectionId: string,
    options?: RequestOptions,
  ): Promise<components["schemas"]["CollectionResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedCollectionResponse"]>({
      method: "GET",
      path: "/v1/marketplace/collections/{collection_id}",
      pathParams: { collection_id: collectionId },
      query: undefined,
      headers: undefined,
      retryable: true,
      httpSemanticallyIdempotent: true,
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    })) as { results: components["schemas"]["CollectionResponse"] };
    return response.results;
  }

  /**
   * Browse public marketplace collections
   *
   * Browse publicly available collections in the marketplace.
   * These collections have 'public_preview' or 'marketplace' access tier.
   *
   * No authentication required, but authenticated users may see more details.
   * @operationId marketplace.listCollections
   * @endpoint GET /v1/marketplace/collections
   */
  async listCollections(
    params: {
  /** Opaque pagination cursor. Pass the ``next_cursor`` from a previous response to fetch the next page. */
  cursor?: string | null;
  /** The maximum number of collections to return */
  limit?: number;
  /** Search query to filter collections by name or description */
  search?: string | null;
} = {},
    options?: RequestOptions,
  ): Promise<components["schemas"]["PaginatedCollectionResponse"]> {
    return this.core.request<components["schemas"]["PaginatedCollectionResponse"]>({
      method: "GET",
      path: "/v1/marketplace/collections",
      pathParams: {},
      query: { cursor: params.cursor, limit: params.limit, search: params.search },
      headers: undefined,
      retryable: true,
      httpSemanticallyIdempotent: true,
      signal: options?.signal,
      timeoutMs: options?.timeoutMs,
    });
  }

}