// AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
// Source: nebula-sdks/openapi/openapi.json + nebula-sdks/config/sdk-resource-map.yaml

import type { components } from "../types.ts";
import type { NebulaCore } from "../runtime/client.ts";

export interface RequestOptions {
  signal?: AbortSignal;
}

export class MemoriesResource {
  constructor(private readonly core: NebulaCore) {}

  /**
   *
   * Append content to an engram
   * 
   * Append content to an existing engram.
   * 
   * **For conversation engrams:**
   * - Provide `messages` array with content, role, and optional metadata
   * - Works like `/conversations/{id}/messages` endpoint
   * 
   * **For document engrams:**
   * - Provide either `raw_text` or `chunks` to append additional content
   * - Content will be processed and added to the engram
   * @operationId memories.append
   * @endpoint POST /v1/memories/{id}/append
   */
  async append(
    params: {
  /** The unique identifier of the engram */
  id: string;
  body: components["schemas"]["AppendMemoryRequest"];
},
    options?: RequestOptions,
  ): Promise<unknown> {
    return this.core.request<unknown>({
      method: "POST",
      path: "/v1/memories/{id}/append",
      pathParams: { id: params.id },
      query: undefined,
      body: params.body,
      idempotent: false,
      signal: options?.signal,
    });
  }

  /**
   *
   * Create a new memory (conversation or document)
   * 
   * Create a new memory (conversation or document) using clean JSON body.
   * 
   * - Use `collection_id` (UUID)
   * - `kind` is optional and inferred from payload shape:
   *   - If `messages` present -> conversation
   *   - Otherwise -> document
   * - For conversations: provide `messages` array
   * - For documents: provide `raw_text` or `chunks`
   * - Use `snapshot` for device-memory mode (mutually exclusive with collection_id)
   * @operationId memories.create
   * @endpoint POST /v1/memories
   */
  async create(
    params: {
  body: components["schemas"]["CreateMemoryRequest"];
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["MemoryCreateResponse"]> {
    return this.core.request<components["schemas"]["MemoryCreateResponse"]>({
      method: "POST",
      path: "/v1/memories",
      pathParams: {},
      query: undefined,
      body: params.body,
      idempotent: false,
      signal: options?.signal,
    });
  }

  /**
   *
   * Get presigned URL for large file upload
   * 
   * Get a presigned URL for uploading large files directly to S3.
   * 
   * Use this for files larger than 5MB that cannot be sent inline as base64.
   * After uploading, reference the file in memory creation using S3FileReference.
   * 
   * Args:
   *     filename: Original filename (e.g., "image.jpg")
   *     content_type: MIME type (e.g., "image/jpeg", "application/pdf")
   *     file_size: Expected file size in bytes (max 100MB)
   * 
   * Returns:
   *     dict with:
   *     - upload_url: Presigned URL for PUT request (expires in 1 hour)
   *     - upload_headers: Headers that must be sent with the presigned PUT request
   *     - s3_key: The S3 key to reference in memory creation
   *     - bucket: S3 bucket name
   *     - expires_in: Seconds until URL expires
   *     - max_size: Maximum allowed file size
   * @operationId memories.createUpload
   * @endpoint POST /v1/memories/upload
   */
  async createUpload(
    params: {
  /** Original filename (e.g., 'image.jpg') */
  filename: string;
  /** MIME type (e.g., 'image/jpeg', 'application/pdf') */
  contentType: string;
  /** Expected file size in bytes (max 100MB) */
  fileSize: number;
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["NebulaResults_PresignedUploadResponse_"]> {
    return this.core.request<components["schemas"]["NebulaResults_PresignedUploadResponse_"]>({
      method: "POST",
      path: "/v1/memories/upload",
      pathParams: {},
      query: { filename: params.filename, content_type: params.contentType, file_size: params.fileSize },
      idempotent: false,
      signal: options?.signal,
    });
  }

  /**
   *
   * Delete an engram
   * 
   * Delete a specific engram with graph awareness. All chunks corresponding to the
   * engram are deleted, and graph components (entities/relationships) are updated
   * or deleted based on remaining chunk references from other engrams.
   * 
   * This method now properly handles graph components and maintains graph integrity
   * for search operations.
   * @operationId memories.delete
   * @endpoint DELETE /v1/memories/{id}
   */
  async delete(
    id: string,
    options?: RequestOptions,
  ): Promise<components["schemas"]["NebulaResults_GenericBooleanResponse_"]> {
    return this.core.request<components["schemas"]["NebulaResults_GenericBooleanResponse_"]>({
      method: "DELETE",
      path: "/v1/memories/{id}",
      pathParams: { id: id },
      query: undefined,
      idempotent: false,
      signal: options?.signal,
    });
  }

  /**
   *
   * Delete one or more engrams
   * 
   * Delete one or more engrams.
   * 
   * This endpoint efficiently handles both single and batch deletions.
   * When multiple IDs are provided, it uses optimized batch operations.
   * 
   * Args:
   *     ids: Either a single UUID or a list of UUIDs to delete
   * 
   * Returns:
   *     For single deletion: boolean success response
   *     For batch deletion: detailed results with successful and failed deletions
   * @operationId memories.deleteMany
   * @endpoint POST /v1/memories/delete
   */
  async deleteMany(
    params: {
  body: components["schemas"]["DeleteMemoriesRequest"];
},
    options?: RequestOptions,
  ): Promise<unknown> {
    return this.core.request<unknown>({
      method: "POST",
      path: "/v1/memories/delete",
      pathParams: {},
      query: undefined,
      body: params.body,
      idempotent: false,
      signal: options?.signal,
    });
  }

  /**
   *
   * Delete a previously uploaded S3 file
   * 
   * Delete a file from S3 that was uploaded via a presigned URL.
   * Verifies the caller owns the file via S3 object metadata.
   * @operationId memories.deleteUpload
   * @endpoint DELETE /v1/memories/upload
   */
  async deleteUpload(
    params: {
  /** S3 key of the file to delete (returned by POST /memories/upload) */
  s3Key: string;
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["NebulaResults_GenericMessageResponse_"]> {
    return this.core.request<components["schemas"]["NebulaResults_GenericMessageResponse_"]>({
      method: "DELETE",
      path: "/v1/memories/upload",
      pathParams: {},
      query: { s3_key: params.s3Key },
      idempotent: false,
      signal: options?.signal,
    });
  }

  /**
   *
   * List engrams
   * 
   * Returns a paginated list of engrams the authenticated user has
   * access to.
   * 
   * Results can be filtered by providing specific engram IDs or collection IDs.
   * Regular users will only see engrams they own or have access to through
   * collections. Superusers can see all engrams.
   * 
   * The engrams are returned in order of last modification, with most
   * recent first. The response includes the engram's text field if available.
   * @operationId memories.list
   * @endpoint GET /v1/memories
   */
  async list(
    params: {
  /** A list of engram IDs to retrieve. If not provided, all engrams will be returned. */
  ids?: Array<string>;
  /** Specifies the number of objects to skip. Defaults to 0. */
  offset?: number;
  /** Specifies a limit on the number of objects to return, ranging between 1 and 1000. Defaults to 100. */
  limit?: number;
  /** Maximum chunks to inline per engram. Defaults to all chunks for backwards compatibility; pass 0 to skip chunk hydration. */
  chunksLimit?: number | null;
  /** If true, only returns engrams owned by the user, not all accessible engrams. */
  ownerOnly?: boolean;
  /** Optional list of collection IDs to filter engrams by. If provided, exactly one collection ID must be specified. */
  collectionIds?: unknown | null;
  /** JSON string for metadata filtering. Example: '{"metadata.source": {"$eq": "playground"}}' */
  metadataFilters?: string | null;
  /** Read-your-writes assertion: the WAL-tail overlay path waits for at least this seq to be applied before serving (or returns 503 Unavailable on timeout). REQUIRES exactly one collection_ids entry — without a collection scope the request returns 422 (the per-WAL-shard scalar applied_wal_seq is meaningless across collections). When the served shard has not been migrated to wal_compaction_enabled, the field is accepted but the served path is the legacy overlay (the assertion has no effect — the response's applied_wal_seq will be 0). Pass back the value the matching upload response surfaced. */
  minAppliedWalSeq?: number | null;
} = {},
    options?: RequestOptions,
  ): Promise<components["schemas"]["WrappedEngramsResponse"]> {
    return this.core.request<components["schemas"]["WrappedEngramsResponse"]>({
      method: "GET",
      path: "/v1/memories",
      pathParams: {},
      query: { ids: params.ids, offset: params.offset, limit: params.limit, chunks_limit: params.chunksLimit, owner_only: params.ownerOnly, collection_ids: params.collectionIds, metadata_filters: params.metadataFilters, min_applied_wal_seq: params.minAppliedWalSeq },
      idempotent: true,
      signal: options?.signal,
    });
  }

  /**
   *
   * Retrieve an engram
   * 
   * Retrieves detailed information about a specific engram by its
   * ID.
   * 
   * This endpoint returns the engram's metadata, status, and system information. It does not
   * return the engram's content - use the `/engrams/{id}/download` endpoint for that.
   * 
   * Users can only retrieve engrams they own or have access to through collections.
   * Superusers can retrieve any engram.
   * @operationId memories.retrieve
   * @endpoint GET /v1/memories/{id}
   */
  async retrieve(
    id: string,
    options?: RequestOptions,
  ): Promise<components["schemas"]["NebulaResults_Engram_"]> {
    return this.core.request<components["schemas"]["NebulaResults_Engram_"]>({
      method: "GET",
      path: "/v1/memories/{id}",
      pathParams: { id: id },
      query: undefined,
      idempotent: true,
      signal: options?.signal,
    });
  }

  /**
   *
   * Search memories
   * 
   * Perform a search query across your memories.
   * 
   * **Standard mode** (collection_ids or readable-scope search): returns hierarchical MemoryRecall
   * with semantics, episodes, procedures, and sources.
   * 
   * **Snapshot mode** (snapshot field): returns graph-search results with
   * {entities, relationships} from stateless in-memory traversal.
   * @operationId memories.search
   * @endpoint POST /v1/memories/search
   */
  async search(
    params: {
  body: components["schemas"]["MemorySearchRequest"];
},
    options?: RequestOptions,
  ): Promise<unknown> {
    return this.core.request<unknown>({
      method: "POST",
      path: "/v1/memories/search",
      pathParams: {},
      query: undefined,
      body: params.body,
      idempotent: false,
      signal: options?.signal,
    });
  }

  /**
   *
   * Update a memory
   * 
   * Update memory-level properties including name, metadata, and collection associations.
   * 
   * This endpoint allows updating properties of an entire memory (document or conversation)
   * without modifying its content:
   * - **name**: Updates the authoritative engram title
   * - **metadata**: Can replace or merge with existing metadata
   * - **collection_ids**: Updates authoritative engram collection associations
   * 
   * Users can only update memories they own or have access to through collections.
   * At least one collection association must be maintained.
   * 
   * If collection_id is provided and the engram is shared across collections, a copy-on-write
   * will be performed to create a collection-specific copy before modification.
   * @operationId memories.update
   * @endpoint PATCH /v1/memories/{id}
   */
  async update(
    params: {
  /** The unique identifier of the memory */
  id: string;
  /** Collection context for copy-on-write. If provided and engram is shared, creates a copy before modification. */
  collectionId?: string | null;
  body: components["schemas"]["UpdateMemoryRequest"];
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["NebulaResults_Engram_"]> {
    return this.core.request<components["schemas"]["NebulaResults_Engram_"]>({
      method: "PATCH",
      path: "/v1/memories/{id}",
      pathParams: { id: params.id },
      query: { collection_id: params.collectionId },
      body: params.body,
      idempotent: false,
      signal: options?.signal,
    });
  }

}