// AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
// Source: nebula-sdks/openapi/openapi.json

import type { components } from "../types.ts";
import type { NebulaCore, RequestOptions } from "../runtime/client.ts";

export class MemoriesResource {
  constructor(private readonly core: NebulaCore) {}

  /**
   * Append content to an engram
   *
   * Append content to an existing engram.
   *
   * **For conversation engrams:**
   * - Provide `messages` array with content, role, and optional metadata
   * - Works like `/conversations/{id}/messages` endpoint
   *
   * **For document engrams:**
   * - Provide either `raw_text` or `chunks` to append additional content
   * - Content will be processed and added to the engram
   * @operationId memories.append
   * @endpoint POST /v1/memories/{id}/append
   */
  async append(
    params: {
  /** The unique identifier of the engram */
  id: string;
  body: components["schemas"]["AppendMemoryRequest"];
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["AppendMemoryResponse"] | components["schemas"]["IngestionResponse"]> {
    const response = (await this.core.request<unknown>({
      method: "POST",
      path: "/v1/memories/{id}/append",
      pathParams: { id: params.id },
      query: undefined,
      body: params.body,
      routing: {
        owner: "collection",
        bodyFields: ["collection_id","collectionId"],
      },
      idempotent: false,
      signal: options?.signal,
    })) as { results: components["schemas"]["AppendMemoryResponse"] | components["schemas"]["IngestionResponse"] };
    return response.results;
  }

  /**
   * Complete multipart upload session
   *
   * Finalize an upload session after every multipart upload part has been uploaded.
   * @operationId memories.completeUpload
   * @endpoint POST /v1/memories/upload/{upload_session_id}/complete
   */
  async completeUpload(
    params: {
  uploadSessionId: string;
  body: components["schemas"]["CompleteMultipartUploadRequest"];
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["CompleteMultipartUploadResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedCompleteMultipartUploadResponse"]>({
      method: "POST",
      path: "/v1/memories/upload/{upload_session_id}/complete",
      pathParams: { upload_session_id: params.uploadSessionId },
      query: undefined,
      body: params.body,
      idempotent: false,
      signal: options?.signal,
    })) as { results: components["schemas"]["CompleteMultipartUploadResponse"] };
    return response.results;
  }

  /**
   * Create a new memory (conversation or document)
   *
   * Create a new memory (conversation or document) using clean JSON body.
   *
   * - Use `collection_id` (UUID)
   * - `kind` is optional and inferred from payload shape:
   *   - If `messages` present -> conversation
   *   - Otherwise -> document
   * - For conversations: provide `messages` array
   * - For documents: provide `raw_text` or `chunks`
   * - Use `snapshot` for device-memory mode (mutually exclusive with collection_id)
   * @operationId memories.create
   * @endpoint POST /v1/memories
   */
  async create(
    body: components["schemas"]["CreateMemoryRequest"],
    options?: RequestOptions,
  ): Promise<components["schemas"]["MemoryCreateAcceptedResponse"] | components["schemas"]["SnapshotMutationResult"]> {
    const response = (await this.core.request<components["schemas"]["MemoryCreateResponse"]>({
      method: "POST",
      path: "/v1/memories",
      pathParams: {},
      query: undefined,
      body: body,
      routing: {
        owner: "collection",
        bodyFields: ["collection_id","collectionId"],
      },
      idempotent: false,
      signal: options?.signal,
    })) as { results: components["schemas"]["MemoryCreateAcceptedResponse"] | components["schemas"]["SnapshotMutationResult"] };
    return response.results;
  }

  /**
   * Create multipart upload session
   *
   * Create a workspace-scoped multipart upload session.
   * @operationId memories.createUpload
   * @endpoint POST /v1/memories/upload
   */
  async createUpload(
    params: {
  /** Original filename (e.g., 'image.jpg') */
  filename: string;
  /** MIME type (e.g., 'image/jpeg', 'application/pdf') */
  contentType: string;
  /** Expected file size in bytes (max 100MB) */
  fileSize: number;
  /** Optional target collection for workspace-scoped uploads. */
  collectionId?: string | null;
  /** Optional workspace for collectionless uploads. Omit to use the caller's personal workspace. */
  workspaceId?: string | null;
  /** Optional client key for retrying upload-session creation. */
  clientIdempotencyKey?: string | null;
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["MultipartUploadSessionResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedMultipartUploadSessionResponse"]>({
      method: "POST",
      path: "/v1/memories/upload",
      pathParams: {},
      query: { filename: params.filename, content_type: params.contentType, file_size: params.fileSize, collection_id: params.collectionId, workspace_id: params.workspaceId, client_idempotency_key: params.clientIdempotencyKey },
      routing: {
        owner: "collection",
        queryFields: ["collection_id","collectionId"],
      },
      idempotent: false,
      signal: options?.signal,
    })) as { results: components["schemas"]["MultipartUploadSessionResponse"] };
    return response.results;
  }

  /**
   * Delete an engram
   *
   * Accept a specific engram for durable deletion.
   * @operationId memories.delete
   * @endpoint DELETE /v1/memories/{id}
   */
  async delete(
    params: {
  /** Engram ID */
  id: string;
  /** Collection context for the deletion. */
  collectionId: string;
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["DeletionOperationAcceptedResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedDeletionOperationAcceptedResponse"]>({
      method: "DELETE",
      path: "/v1/memories/{id}",
      pathParams: { id: params.id },
      query: { collection_id: params.collectionId },
      headers: options?.idempotencyKey ? { "Idempotency-Key": options.idempotencyKey } : undefined,
      routing: {
        owner: "collection",
        queryFields: ["collection_id","collectionId"],
      },
      idempotent: Boolean(options?.idempotencyKey),
      signal: options?.signal,
    })) as { results: components["schemas"]["DeletionOperationAcceptedResponse"] };
    return response.results;
  }

  /**
   * Delete one or more engrams
   *
   * Accept one or more engrams for durable deletion.
   * @operationId memories.deleteMany
   * @endpoint POST /v1/memories/delete
   */
  async deleteMany(
    body: components["schemas"]["DeleteMemoriesRequest"],
    options?: RequestOptions,
  ): Promise<components["schemas"]["DeletionOperationAcceptedResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedDeletionOperationAcceptedResponse"]>({
      method: "POST",
      path: "/v1/memories/delete",
      pathParams: {},
      query: undefined,
      body: body,
      headers: options?.idempotencyKey ? { "Idempotency-Key": options.idempotencyKey } : undefined,
      routing: {
        owner: "collection",
        bodyFields: ["collection_id","collectionId"],
      },
      idempotent: Boolean(options?.idempotencyKey),
      signal: options?.signal,
    })) as { results: components["schemas"]["DeletionOperationAcceptedResponse"] };
    return response.results;
  }

  /**
   * Delete a pending upload session
   *
   * Delete a pending upload session and its staged object.
   * @operationId memories.deleteUpload
   * @endpoint DELETE /v1/memories/upload
   */
  async deleteUpload(
    params: {
  /** Upload session ID returned by memories.createUpload. */
  uploadSessionId: string;
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["GenericMessageResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedGenericMessageResponse"]>({
      method: "DELETE",
      path: "/v1/memories/upload",
      pathParams: {},
      query: { upload_session_id: params.uploadSessionId },
      idempotent: true,
      signal: options?.signal,
    })) as { results: components["schemas"]["GenericMessageResponse"] };
    return response.results;
  }

  /**
   * Get memory deletion status
   *
   * Return the current state and per-target outcomes for a memory deletion operation.
   * @operationId memories.getDeletion
   * @endpoint GET /v1/memories/deletions/{operation_id}
   */
  async getDeletion(
    operationId: string,
    options?: RequestOptions,
  ): Promise<components["schemas"]["DeletionOperationResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedDeletionOperationResponse"]>({
      method: "GET",
      path: "/v1/memories/deletions/{operation_id}",
      pathParams: { operation_id: operationId },
      query: undefined,
      idempotent: true,
      signal: options?.signal,
    })) as { results: components["schemas"]["DeletionOperationResponse"] };
    return response.results;
  }

  /**
   * List engrams
   *
   * Returns a cursor-paginated list of engrams the authenticated user
   * has access to.
   *
   * Results can be filtered by providing specific engram IDs or collection IDs.
   * Regular users will only see engrams they own or have access to through
   * collections. Superusers can see all engrams.
   *
   * The engrams are returned in order of creation time, most recent
   * first. The response includes the engram's text field if available.
   * @operationId memories.list
   * @endpoint GET /v1/memories
   */
  async list(
    params: {
  /** A list of engram IDs to retrieve. If not provided, all engrams will be returned. */
  ids?: Array<string>;
  /** Opaque pagination cursor. Pass the ``next_cursor`` from a previous response to fetch the next page. */
  cursor?: string | null;
  /** Specifies a limit on the number of objects to return, ranging between 1 and 1000. Defaults to 100. */
  limit?: number;
  /** Maximum chunks to inline per engram. Defaults to all chunks for backwards compatibility; pass 0 to skip chunk hydration. */
  chunksLimit?: number | null;
  /** If true, only returns engrams owned by the user, not all accessible engrams. */
  ownerOnly?: boolean;
  /** Optional list of collection IDs to filter engrams by. If provided, exactly one collection ID must be specified. */
  collectionIds?: Array<string> | null;
  /** JSON string for metadata filtering. Example: '{"metadata.source": {"$eq": "playground"}}' */
  metadataFilters?: string | null;
} = {},
    options?: RequestOptions,
  ): Promise<components["schemas"]["PaginatedListedEngram"]> {
    return this.core.request<components["schemas"]["PaginatedListedEngram"]>({
      method: "GET",
      path: "/v1/memories",
      pathParams: {},
      query: { ids: params.ids, cursor: params.cursor, limit: params.limit, chunks_limit: params.chunksLimit, owner_only: params.ownerOnly, collection_ids: params.collectionIds, metadata_filters: params.metadataFilters },
      idempotent: true,
      signal: options?.signal,
    });
  }

  /**
   * Recall workflow patterns by intent
   *
   * Workflow-pattern recall over 5 intents.
   *
   * * ``cursor`` -- match the caller's anchor against pattern
   *   canonical states, return ranked patterns + position.
   * * ``predict`` -- like cursor but include the predicted next
   *   trace from each pattern's canonical instance.
   * * ``resume`` -- like cursor, biased toward longer patterns.
   * * ``evidence`` -- expand a specific pattern via
   *   ``hydrate_pattern``.
   * * ``bootstrap`` -- top-K patterns by confidence with no anchor.
   * @operationId memories.recallWorkflow
   * @endpoint POST /v1/memories/workflow/recall
   */
  async recallWorkflow(
    body: components["schemas"]["CursorRecallRequest"] | components["schemas"]["PredictRecallRequest"] | components["schemas"]["ResumeRecallRequest"] | components["schemas"]["EvidenceRecallRequest"] | components["schemas"]["BootstrapRecallRequest"],
    options?: RequestOptions,
  ): Promise<Record<string, unknown>> {
    const response = (await this.core.request<components["schemas"]["WorkflowRecallResponse"]>({
      method: "POST",
      path: "/v1/memories/workflow/recall",
      pathParams: {},
      query: undefined,
      body: body,
      idempotent: false,
      signal: options?.signal,
    })) as { results: Record<string, unknown> };
    return response.results;
  }

  /**
   * Resolve sources for an audited memory search
   *
   * Hydrate stored evidence refs after rechecking current access.
   * @operationId memories.resolveSearchSources
   * @endpoint GET /v1/memories/searches/{retrieval_id}/sources
   */
  async resolveSearchSources(
    retrievalId: string,
    options?: RequestOptions,
  ): Promise<components["schemas"]["RetrievalAuditSourcesResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedRetrievalAuditSourcesResponse"]>({
      method: "GET",
      path: "/v1/memories/searches/{retrieval_id}/sources",
      pathParams: { retrieval_id: retrievalId },
      query: undefined,
      idempotent: true,
      signal: options?.signal,
    })) as { results: components["schemas"]["RetrievalAuditSourcesResponse"] };
    return response.results;
  }

  /**
   * Retrieve an engram
   *
   * Retrieves detailed information about a specific engram by its
   * ID.
   *
   * This endpoint returns the engram's metadata, status, and system information. It does not
   * return the engram's content - use the `/engrams/{id}/download` endpoint for that.
   *
   * Users can only retrieve engrams they own or have access to through collections.
   * Superusers can retrieve any engram.
   * @operationId memories.retrieve
   * @endpoint GET /v1/memories/{id}
   */
  async retrieve(
    id: string,
    options?: RequestOptions,
  ): Promise<components["schemas"]["Engram"]> {
    const response = (await this.core.request<components["schemas"]["WrappedEngram"]>({
      method: "GET",
      path: "/v1/memories/{id}",
      pathParams: { id: id },
      query: undefined,
      idempotent: true,
      signal: options?.signal,
    })) as { results: components["schemas"]["Engram"] };
    return response.results;
  }

  /**
   * Search memories
   *
   * Perform a search query across your memories.
   *
   * **Standard mode** (collection_ids or readable-scope search): returns hierarchical MemoryRecall
   * with semantics, episodes, and procedures. Set ``include_sources``
   * to include the raw source material grounding the retrieved memory.
   *
   * **Snapshot mode** (snapshot field): returns graph-search results with
   * {entities, relationships} from stateless in-memory traversal.
   * @operationId memories.search
   * @endpoint POST /v1/memories/search
   */
  async search(
    body: components["schemas"]["MemorySearchRequest"],
    options?: RequestOptions,
  ): Promise<components["schemas"]["CompactMemoryRecallResponse"] | components["schemas"]["MemoryRecall"] | components["schemas"]["SnapshotSearchResult"]> {
    const response = (await this.core.request<unknown>({
      method: "POST",
      path: "/v1/memories/search",
      pathParams: {},
      query: undefined,
      body: body,
      routing: {
        owner: "collection",
        bodyFields: ["collection_ids","collectionIds","filters.collection_id","filters.collection_ids","search_settings.filters.collection_id","search_settings.filters.collection_ids"],
      },
      idempotent: false,
      signal: options?.signal,
    })) as { results: components["schemas"]["CompactMemoryRecallResponse"] | components["schemas"]["MemoryRecall"] | components["schemas"]["SnapshotSearchResult"] };
    return response.results;
  }

  /**
   * Create multipart upload part URL
   *
   * Create a presigned URL for uploading one part of an existing memory upload session.
   * @operationId memories.signUploadPart
   * @endpoint POST /v1/memories/upload/{upload_session_id}/parts/{part_number}
   */
  async signUploadPart(
    params: {
  uploadSessionId: string;
  partNumber: number;
  /** Base64-encoded SHA-256 checksum for this part. */
  checksumSha256: string;
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["MultipartUploadPartResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedMultipartUploadPartResponse"]>({
      method: "POST",
      path: "/v1/memories/upload/{upload_session_id}/parts/{part_number}",
      pathParams: { upload_session_id: params.uploadSessionId, part_number: params.partNumber },
      query: { checksum_sha256: params.checksumSha256 },
      idempotent: false,
      signal: options?.signal,
    })) as { results: components["schemas"]["MultipartUploadPartResponse"] };
    return response.results;
  }

  /**
   * Update a memory
   *
   * Update memory-level properties including name, metadata, and collection associations.
   *
   * This endpoint allows updating properties of an entire memory (document or conversation)
   * without modifying its content:
   * - **name**: Updates the authoritative engram title
   * - **metadata**: Can replace or merge with existing metadata
   * - **collection_ids**: Updates authoritative engram collection associations
   *
   * Users can only update memories they own or have access to through collections.
   * At least one collection association must be maintained.
   *
   * If collection_id is provided and the engram is shared across collections, a copy-on-write
   * will be performed to create a collection-specific copy before modification.
   * @operationId memories.update
   * @endpoint PATCH /v1/memories/{id}
   */
  async update(
    params: {
  /** The unique identifier of the memory */
  id: string;
  /** Collection context for copy-on-write. If provided and engram is shared, creates a copy before modification. */
  collectionId: string;
  body: components["schemas"]["UpdateMemoryRequest"];
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["Engram"]> {
    const response = (await this.core.request<components["schemas"]["WrappedEngram"]>({
      method: "PATCH",
      path: "/v1/memories/{id}",
      pathParams: { id: params.id },
      query: { collection_id: params.collectionId },
      body: params.body,
      routing: {
        owner: "collection",
        queryFields: ["collection_id","collectionId"],
      },
      idempotent: false,
      signal: options?.signal,
    })) as { results: components["schemas"]["Engram"] };
    return response.results;
  }

}