// AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
// Source: nebula-sdks/openapi/openapi.json + nebula-sdks/config/sdk-resource-map.yaml

import type { components } from "../types.ts";
import type { NebulaCore } from "../runtime/client.ts";

export interface RequestOptions {
  signal?: AbortSignal;
}

export class SnapshotsResource {
  constructor(private readonly core: NebulaCore) {}

  /**
   *
   * Export a collection snapshot
   * 
   * Export a collection's full graph state as a
   * portable SnapshotEnvelope.
   * @operationId snapshots.export
   * @endpoint POST /v1/device-memory/snapshot/export
   */
  async export(
    params: {
  body: components["schemas"]["SnapshotExportRequest"];
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["NebulaResults_SnapshotEnvelope_"]> {
    return this.core.request<components["schemas"]["NebulaResults_SnapshotEnvelope_"]>({
      method: "POST",
      path: "/v1/device-memory/snapshot/export",
      pathParams: {},
      query: undefined,
      body: params.body,
      idempotent: false,
      signal: options?.signal,
    });
  }

  /**
   *
   * Import a snapshot into an ephemeral collection
   * 
   * Import a SnapshotEnvelope into an ephemeral
   * collection. Returns the ephemeral collection UUID.
   * @operationId snapshots.import
   * @endpoint POST /v1/device-memory/snapshot/import
   */
  async import(
    params: {
  body: components["schemas"]["SnapshotImportRequest"];
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["NebulaResults_SnapshotImportResult_"]> {
    return this.core.request<components["schemas"]["NebulaResults_SnapshotImportResult_"]>({
      method: "POST",
      path: "/v1/device-memory/snapshot/import",
      pathParams: {},
      query: undefined,
      body: params.body,
      idempotent: false,
      signal: options?.signal,
    });
  }

}