// AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
// Source: nebula-sdks/openapi/openapi.json

import type { components } from "../types.ts";
import type { NebulaCore } from "../runtime/client.ts";

export interface RequestOptions {
  signal?: AbortSignal;
}

export class SnapshotsResource {
  constructor(private readonly core: NebulaCore) {}

  /**
   *
   * Export a collection snapshot
   * 
   * Export a collection's full graph state as a
   * portable SnapshotEnvelope.
   * @operationId snapshots.export
   * @endpoint POST /v1/device-memory/snapshot/export
   */
  async export(
    body: components["schemas"]["SnapshotExportRequest"],
    options?: RequestOptions,
  ): Promise<components["schemas"]["SnapshotEnvelope-Output"]> {
    const response = (await this.core.request<components["schemas"]["WrappedSnapshotEnvelope"]>({
      method: "POST",
      path: "/v1/device-memory/snapshot/export",
      pathParams: {},
      query: undefined,
      body: body,
      idempotent: true,
      signal: options?.signal,
    })) as { results: components["schemas"]["SnapshotEnvelope-Output"] };
    return response.results;
  }

  /**
   *
   * Import a snapshot into an ephemeral collection
   * 
   * Import a SnapshotEnvelope into an ephemeral
   * collection. Returns the ephemeral collection UUID.
   * @operationId snapshots.import
   * @endpoint POST /v1/device-memory/snapshot/import
   */
  async import(
    body: components["schemas"]["SnapshotImportRequest"],
    options?: RequestOptions,
  ): Promise<components["schemas"]["SnapshotImportResult"]> {
    const response = (await this.core.request<components["schemas"]["WrappedSnapshotImportResult"]>({
      method: "POST",
      path: "/v1/device-memory/snapshot/import",
      pathParams: {},
      query: undefined,
      body: body,
      idempotent: false,
      signal: options?.signal,
    })) as { results: components["schemas"]["SnapshotImportResult"] };
    return response.results;
  }

}