// AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
// Source: nebula-sdks/openapi/openapi.json

import type { components } from "../types.ts";
import type { NebulaCore, RequestOptions } from "../runtime/client.ts";

export class WorkspacesResource {
  constructor(private readonly core: NebulaCore) {}

  /**
   * Create workspace storage target
   *
   * Register a customer S3 bucket for hosted BYOC storage.
   * @operationId workspaces.createStorageTarget
   * @endpoint POST /v1/workspaces/{workspace_id}/storage-targets
   */
  async createStorageTarget(
    params: {
  workspaceId: string;
  body: components["schemas"]["StorageTargetCreateRequest"];
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["StorageTargetResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedStorageTargetResponse"]>({
      method: "POST",
      path: "/v1/workspaces/{workspace_id}/storage-targets",
      pathParams: { workspace_id: params.workspaceId },
      query: undefined,
      body: params.body,
      idempotent: false,
      signal: options?.signal,
    })) as { results: components["schemas"]["StorageTargetResponse"] };
    return response.results;
  }

  /**
   * Disable workspace storage target
   *
   * Disable a customer storage target for future collection binds.
   * @operationId workspaces.disableStorageTarget
   * @endpoint DELETE /v1/workspaces/{workspace_id}/storage-targets/{target_id}
   */
  async disableStorageTarget(
    params: {
  workspaceId: string;
  targetId: string;
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["StorageTargetResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedStorageTargetResponse"]>({
      method: "DELETE",
      path: "/v1/workspaces/{workspace_id}/storage-targets/{target_id}",
      pathParams: { workspace_id: params.workspaceId, target_id: params.targetId },
      query: undefined,
      idempotent: false,
      signal: options?.signal,
    })) as { results: components["schemas"]["StorageTargetResponse"] };
    return response.results;
  }

  /**
   * List workspace storage targets
   *
   * List customer-owned object storage targets for a workspace.
   * @operationId workspaces.listStorageTargets
   * @endpoint GET /v1/workspaces/{workspace_id}/storage-targets
   */
  async listStorageTargets(
    workspaceId: string,
    options?: RequestOptions,
  ): Promise<Array<components["schemas"]["StorageTargetResponse"]>> {
    const response = (await this.core.request<components["schemas"]["WrappedListOfStorageTargetResponse"]>({
      method: "GET",
      path: "/v1/workspaces/{workspace_id}/storage-targets",
      pathParams: { workspace_id: workspaceId },
      query: undefined,
      idempotent: true,
      signal: options?.signal,
    })) as { results: Array<components["schemas"]["StorageTargetResponse"]> };
    return response.results;
  }

  /**
   * Validate workspace storage target
   *
   * Probe a customer storage target and mark it active on success.
   * @operationId workspaces.validateStorageTarget
   * @endpoint POST /v1/workspaces/{workspace_id}/storage-targets/{target_id}/validate
   */
  async validateStorageTarget(
    params: {
  workspaceId: string;
  targetId: string;
},
    options?: RequestOptions,
  ): Promise<components["schemas"]["StorageTargetResponse"]> {
    const response = (await this.core.request<components["schemas"]["WrappedStorageTargetResponse"]>({
      method: "POST",
      path: "/v1/workspaces/{workspace_id}/storage-targets/{target_id}/validate",
      pathParams: { workspace_id: params.workspaceId, target_id: params.targetId },
      query: undefined,
      idempotent: false,
      signal: options?.signal,
    })) as { results: components["schemas"]["StorageTargetResponse"] };
    return response.results;
  }

}