// AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
// Source: nebula-sdks/config/dx-extensions.yaml

import { NebulaClient } from "../client.ts";

/** Unwrap the {results: T} envelope when present. */
function unwrap<T>(p: Promise<T>): Promise<unknown> {
  return p.then((r) => {
    if (r !== null && typeof r === "object" && "results" in r) {
      return (r as { results: unknown }).results;
    }
    return r;
  });
}

/**
 * Generated DX layer: simple unwrap/passthrough convenience methods.
 * The handwritten Nebula class extends this with complex methods.
 */
export class NebulaDX extends NebulaClient {
  /** Retrieve a single memory by id and return just the data. (generated from dx-extensions.yaml). */
  async getMemory(id: string, options?: { signal?: AbortSignal }): Promise<unknown> {
    return unwrap(this.memories.retrieve(id, options));
  }

  /** Update a memory by id; returns the updated record. (generated from dx-extensions.yaml). */
  async updateMemory(args: Record<string, unknown>, options?: { signal?: AbortSignal }): Promise<unknown> {
    return unwrap(this.memories.update((args ?? {}) as never, options));
  }

  /** Liveness probe with the wire envelope unwrapped. (generated from dx-extensions.yaml). */
  async healthCheck(options?: { signal?: AbortSignal }): Promise<unknown> {
    return unwrap(this.client.health(options));
  }

  /** unwrap → collections.create (generated from dx-extensions.yaml). */
  async createCollection(args: Record<string, unknown>, options?: { signal?: AbortSignal }): Promise<unknown> {
    return unwrap(this.collections.create((args ?? {}) as never, options));
  }

  /** unwrap → collections.retrieve (generated from dx-extensions.yaml). */
  async getCollection(id: string, options?: { signal?: AbortSignal }): Promise<unknown> {
    return unwrap(this.collections.retrieve(id, options));
  }

  /** unwrap → collections.retrieveByName (generated from dx-extensions.yaml). */
  async getCollectionByName(args: Record<string, unknown>, options?: { signal?: AbortSignal }): Promise<unknown> {
    return unwrap(this.collections.retrieveByName((args ?? {}) as never, options));
  }

  /** unwrap → collections.list (generated from dx-extensions.yaml). */
  async listCollections(args?: Record<string, unknown>, options?: { signal?: AbortSignal }): Promise<unknown> {
    return unwrap(this.collections.list((args ?? {}) as never, options));
  }

  /** unwrap → collections.update (generated from dx-extensions.yaml). */
  async updateCollection(args: Record<string, unknown>, options?: { signal?: AbortSignal }): Promise<unknown> {
    return unwrap(this.collections.update((args ?? {}) as never, options));
  }

  /** unwrap → connectors.listProviders (generated from dx-extensions.yaml). */
  async listProviders(options?: { signal?: AbortSignal }): Promise<unknown> {
    return unwrap(this.connectors.listProviders(options));
  }

  /** unwrap → connectors.retrieve (generated from dx-extensions.yaml). */
  async getConnection(connectionId: string, options?: { signal?: AbortSignal }): Promise<unknown> {
    return unwrap(this.connectors.retrieve(connectionId, options));
  }

  /** unwrap → connectors.sync (generated from dx-extensions.yaml). */
  async triggerSync(connectionId: string, options?: { signal?: AbortSignal }): Promise<unknown> {
    return unwrap(this.connectors.sync(connectionId, options));
  }

  /** unwrap → memories.createUpload (generated from dx-extensions.yaml). */
  async getUploadUrl(args: Record<string, unknown>, options?: { signal?: AbortSignal }): Promise<unknown> {
    return unwrap(this.memories.createUpload((args ?? {}) as never, options));
  }

  /** unwrap → snapshots.export (generated from dx-extensions.yaml). */
  async exportSnapshot(args: Record<string, unknown>, options?: { signal?: AbortSignal }): Promise<unknown> {
    return unwrap(this.snapshots.export((args ?? {}) as never, options));
  }

  /** unwrap → snapshots.import (generated from dx-extensions.yaml). */
  async importSnapshot(args: Record<string, unknown>, options?: { signal?: AbortSignal }): Promise<unknown> {
    return unwrap(this.snapshots.import((args ?? {}) as never, options));
  }

}