// AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
// Source: nebula-sdks/config/dx-extensions.yaml

import { NebulaClient } from "../client.ts";

/**
 * Conditional type matching the runtime envelope-unwrap. If T has a
 * `results` field, narrow to it; otherwise pass through.
 */
type Unwrapped<T> = T extends { results: infer R } ? R : T;

/** Strip a `results` envelope at runtime; matches `Unwrapped<>`. */
function unwrap<T>(p: Promise<T>): Promise<Unwrapped<T>> {
  return p.then((r) => {
    if (r !== null && typeof r === "object" && "results" in r) {
      return (r as { results: unknown }).results as Unwrapped<T>;
    }
    return r as Unwrapped<T>;
  });
}

/**
 * Generated DX layer: simple unwrap/passthrough convenience methods.
 * Signatures are derived from the underlying resource methods so
 * callers see the same arg names + types in IDE hover.
 */
export class NebulaDX extends NebulaClient {
  /** Retrieve a single memory by id and return just the data. (generated from dx-extensions.yaml). */
  async getMemory(...args: Parameters<NebulaClient["memories"]["retrieve"]>): Promise<Unwrapped<Awaited<ReturnType<NebulaClient["memories"]["retrieve"]>>>> {
    return unwrap<Awaited<ReturnType<NebulaClient["memories"]["retrieve"]>>>(this.memories.retrieve(...args));
  }

  /** Update a memory by id; returns the updated record. (generated from dx-extensions.yaml). */
  async updateMemory(...args: Parameters<NebulaClient["memories"]["update"]>): Promise<Unwrapped<Awaited<ReturnType<NebulaClient["memories"]["update"]>>>> {
    return unwrap<Awaited<ReturnType<NebulaClient["memories"]["update"]>>>(this.memories.update(...args));
  }

  /** Liveness probe with the wire envelope unwrapped. (generated from dx-extensions.yaml). */
  async healthCheck(...args: Parameters<NebulaClient["client"]["health"]>): Promise<Unwrapped<Awaited<ReturnType<NebulaClient["client"]["health"]>>>> {
    return unwrap<Awaited<ReturnType<NebulaClient["client"]["health"]>>>(this.client.health(...args));
  }

  /** unwrap → collections.create (generated from dx-extensions.yaml). */
  async createCollection(...args: Parameters<NebulaClient["collections"]["create"]>): Promise<Unwrapped<Awaited<ReturnType<NebulaClient["collections"]["create"]>>>> {
    return unwrap<Awaited<ReturnType<NebulaClient["collections"]["create"]>>>(this.collections.create(...args));
  }

  /** unwrap → collections.retrieve (generated from dx-extensions.yaml). */
  async getCollection(...args: Parameters<NebulaClient["collections"]["retrieve"]>): Promise<Unwrapped<Awaited<ReturnType<NebulaClient["collections"]["retrieve"]>>>> {
    return unwrap<Awaited<ReturnType<NebulaClient["collections"]["retrieve"]>>>(this.collections.retrieve(...args));
  }

  /** unwrap → collections.retrieveByName (generated from dx-extensions.yaml). */
  async getCollectionByName(...args: Parameters<NebulaClient["collections"]["retrieveByName"]>): Promise<Unwrapped<Awaited<ReturnType<NebulaClient["collections"]["retrieveByName"]>>>> {
    return unwrap<Awaited<ReturnType<NebulaClient["collections"]["retrieveByName"]>>>(this.collections.retrieveByName(...args));
  }

  /** unwrap → collections.list (generated from dx-extensions.yaml). */
  async listCollections(...args: Parameters<NebulaClient["collections"]["list"]>): Promise<Unwrapped<Awaited<ReturnType<NebulaClient["collections"]["list"]>>>> {
    return unwrap<Awaited<ReturnType<NebulaClient["collections"]["list"]>>>(this.collections.list(...args));
  }

  /** unwrap → collections.update (generated from dx-extensions.yaml). */
  async updateCollection(...args: Parameters<NebulaClient["collections"]["update"]>): Promise<Unwrapped<Awaited<ReturnType<NebulaClient["collections"]["update"]>>>> {
    return unwrap<Awaited<ReturnType<NebulaClient["collections"]["update"]>>>(this.collections.update(...args));
  }

  /** unwrap → connectors.listProviders (generated from dx-extensions.yaml). */
  async listProviders(...args: Parameters<NebulaClient["connectors"]["listProviders"]>): Promise<Unwrapped<Awaited<ReturnType<NebulaClient["connectors"]["listProviders"]>>>> {
    return unwrap<Awaited<ReturnType<NebulaClient["connectors"]["listProviders"]>>>(this.connectors.listProviders(...args));
  }

  /** unwrap → connectors.retrieve (generated from dx-extensions.yaml). */
  async getConnection(...args: Parameters<NebulaClient["connectors"]["retrieve"]>): Promise<Unwrapped<Awaited<ReturnType<NebulaClient["connectors"]["retrieve"]>>>> {
    return unwrap<Awaited<ReturnType<NebulaClient["connectors"]["retrieve"]>>>(this.connectors.retrieve(...args));
  }

  /** unwrap → connectors.sync (generated from dx-extensions.yaml). */
  async triggerSync(...args: Parameters<NebulaClient["connectors"]["sync"]>): Promise<Unwrapped<Awaited<ReturnType<NebulaClient["connectors"]["sync"]>>>> {
    return unwrap<Awaited<ReturnType<NebulaClient["connectors"]["sync"]>>>(this.connectors.sync(...args));
  }

  /** unwrap → memories.createUpload (generated from dx-extensions.yaml). */
  async getUploadUrl(...args: Parameters<NebulaClient["memories"]["createUpload"]>): Promise<Unwrapped<Awaited<ReturnType<NebulaClient["memories"]["createUpload"]>>>> {
    return unwrap<Awaited<ReturnType<NebulaClient["memories"]["createUpload"]>>>(this.memories.createUpload(...args));
  }

  /** unwrap → snapshots.export (generated from dx-extensions.yaml). */
  async exportSnapshot(...args: Parameters<NebulaClient["snapshots"]["export"]>): Promise<Unwrapped<Awaited<ReturnType<NebulaClient["snapshots"]["export"]>>>> {
    return unwrap<Awaited<ReturnType<NebulaClient["snapshots"]["export"]>>>(this.snapshots.export(...args));
  }

  /** unwrap → snapshots.import (generated from dx-extensions.yaml). */
  async importSnapshot(...args: Parameters<NebulaClient["snapshots"]["import"]>): Promise<Unwrapped<Awaited<ReturnType<NebulaClient["snapshots"]["import"]>>>> {
    return unwrap<Awaited<ReturnType<NebulaClient["snapshots"]["import"]>>>(this.snapshots.import(...args));
  }

}