// AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
// Source: nebula-sdks/openapi/openapi.json

import { NebulaCore, type ClientOptions } from "./runtime/client.ts";
import { ClientResource } from "./resources/client.ts";
import { CollectionsResource } from "./resources/collections.ts";
import { ConnectorsResource } from "./resources/connectors.ts";
import { MarketplaceResource } from "./resources/marketplace.ts";
import { MemoryResource } from "./resources/memory.ts";
import { SnapshotsResource } from "./resources/snapshots.ts";
import { WorkspacesResource } from "./resources/workspaces.ts";

export class NebulaClient {
  protected readonly core: NebulaCore;
  readonly client: ClientResource;
  readonly collections: CollectionsResource;
  readonly connectors: ConnectorsResource;
  readonly marketplace: MarketplaceResource;
  readonly memory: MemoryResource;
  readonly snapshots: SnapshotsResource;
  readonly workspaces: WorkspacesResource;

  constructor(options: ClientOptions = {}) {
    this.core = new NebulaCore(options);
    this.client = new ClientResource(this.core);
    this.collections = new CollectionsResource(this.core);
    this.connectors = new ConnectorsResource(this.core);
    this.marketplace = new MarketplaceResource(this.core);
    this.memory = new MemoryResource(this.core);
    this.snapshots = new SnapshotsResource(this.core);
    this.workspaces = new WorkspacesResource(this.core);
  }
}