// AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
// Source: nebula-sdks/openapi/openapi.json + nebula-sdks/config/sdk-resource-map.yaml

import { NebulaCore, type ClientOptions } from "./runtime/client.ts";
import { ClientResource } from "./resources/client.ts";
import { CollectionsResource } from "./resources/collections.ts";
import { ConnectorsResource } from "./resources/connectors.ts";
import { MemoriesResource } from "./resources/memories.ts";
import { SnapshotsResource } from "./resources/snapshots.ts";

export class NebulaClient {
  protected readonly core: NebulaCore;
  readonly client: ClientResource;
  readonly collections: CollectionsResource;
  readonly connectors: ConnectorsResource;
  readonly memories: MemoriesResource;
  readonly snapshots: SnapshotsResource;

  constructor(options: ClientOptions = {}) {
    this.core = new NebulaCore(options);
    this.client = new ClientResource(this.core);
    this.collections = new CollectionsResource(this.core);
    this.connectors = new ConnectorsResource(this.core);
    this.memories = new MemoriesResource(this.core);
    this.snapshots = new SnapshotsResource(this.core);
  }
}